backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "data/productos"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Precio", name: "precio", widget: "number" }
      - { label: "Material", name: "material", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }